// Guidance system removed during caller-wraps streaming architecture refactor
// pub mod guidance;

pub mod context;
pub mod dispatch;
pub mod errors;
pub mod hub_context;
pub mod method_enum;
pub mod middleware;
pub mod path;
pub mod plexus;
pub mod schema;
pub mod streaming;
pub mod types;

pub use context::PlexusContext;
#[deprecated(note = "Use GuidanceErrorType and GuidanceSuggestion from stream events instead")]
pub use errors::{GuidedError, GuidedErrorData, TryRequest};
#[deprecated(note = "Middleware removed - guidance provided via PlexusStreamEvent::Guidance")]
pub use middleware::{ActivationRegistry, GuidedErrorMiddleware};
pub use path::Provenance;
pub use plexus::{Activation, ActivationInfo, ChildRouter, DynamicHub, PlexusError, TransportErrorKind, route_to_child};
pub use crate::types::Handle;
pub use schema::{ChildHashes, ChildSummary, MethodSchema, PluginHashes, PluginSchema, Schema, SchemaProperty, SchemaResult, SchemaType};
pub use types::{PlexusStreamItem, StreamMetadata};
pub use method_enum::MethodEnumSchema;
pub use streaming::{PlexusStream, wrap_stream, error_stream, done_stream, progress_stream};
// Note: Method enum is auto-generated by hub_macro and exported from plexus module
pub use dispatch::{HubDispatch, StreamItem, from_dispatch_stream};
pub use hub_context::{HubContext, ParentAware, NoParent};
